---
# ─── Variables OpenVPN client ─────────────────────────────────
openvpn_server_ip: 192.168.230.138
openvpn_port: 1194
openvpn_proto: udp
openvpn_cipher: AES-256-GCM
openvpn_auth: SHA256
openvpn_verbosity: 3
